version: '3.7'

services:
  api-solid-pg:
    image: bitnami/postgresql:latest
    container_name: api-solid-pg
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=api-solid-db
